name: Apply patch from issue

on:
  issues:
    types: [labeled, edited]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    # Dispara si el issue tiene la etiqueta apply-patch o si alguien comenta /apply-patch
    if: >
      (github.event_name == 'issues' &&
       contains(join(github.event.issue.labels.*.name, ','), 'apply-patch'))
      || (github.event_name == 'issue_comment' &&
          contains(github.event.comment.body || '', '/apply-patch'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extraer bloque ```patch``` del issue/comentario
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // body del issue o del comentario (si vino por issue_comment)
            const body =
              (context.payload.issue && context.payload.issue.body) ||
              (context.payload.comment && context.payload.comment.body) ||
              '';

            // Busca un bloque con ```patch ... ```
            const m = body.match(/```patch\s*([\s\S]*?)```/i);
            if (!m) {
              core.setFailed('No se encontró un bloque ```patch``` en el issue/comentario.');
              return;
            }

            const patch = m[1].trim() + '\n';
            fs.writeFileSync('changes.patch', patch, 'utf8');

            // Nombre de rama único por issue
            const branch = `patch/issue-${context.payload.issue.number}-${Date.now()}`;
            core.setOutput('branch', branch);

      - name: Crear rama y aplicar patch
        run: |
          set -e
          BRANCH="${{ steps.extract.outputs.branch }}"
          git config user.name  "patch-bot"
          git config user.email "patch-bot@users.noreply.github.com"
          git checkout -b "$BRANCH"

          echo "Aplicando changes.patch…"
          # Intenta aplicar directo; si falla, intenta 3-way
          if ! git apply --whitespace=fix -p0 changes.patch; then
            echo "Patch simple falló, intentando 3-way…"
            git apply --3way changes.patch
          fi

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract.outputs.branch }}
          commit-message: "Apply patch from issue #${{ github.event.issue.number }}"
          title: "Apply patch from issue #${{ github.event.issue.number }}"
          body: |
            This PR was created automatically from issue #${{ github.event.issue.number }}.
            It applies the patch that was included in a ```patch``` fenced block.
          labels: automated, patch-bot
