name: Apply patch from issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  apply:
    # Solo corre si el issue tiene la etiqueta "apply-patch"
    if: contains(github.event.issue.labels.*.name, 'apply-patch')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout (historia completa)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ✅ Tomamos la rama base del payload del evento (main/master, lo que tenga el repo)
      - name: Definir rama base (desde evento)
        id: base
        shell: bash
        run: |
          echo "default_branch=${{ github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"
          echo "Base branch: ${{ github.event.repository.default_branch }}"

      - name: Extraer bloque ```patch``` del issue/comentarios
        id: patch
        shell: bash
        run: |
          python3 - <<'PY'
          import os, re, sys
          body = os.environ.get('ISSUE_BODY') or ''
          m = re.search(r"```patch\s+([\s\S]*?)```", body, re.M|re.S)
          if not m:
              print("::error::No se encontró bloque ```patch``` en el issue.")
              sys.exit(1)
          open('changes.patch','w').write(m.group(1).strip()+"\n")
          PY
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Crear rama de trabajo y aplicar patch
        id: apply_patch
        shell: bash
        run: |
          set -e
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH="patch/issue-${{ github.event.issue.number }}-${{ github.run_id }}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b "$BRANCH"

          # Intento normal, si falla probamos 3-way
          if ! git apply --whitespace=fix changes.patch; then
            echo "Aplicación simple falló; intentando 3-way…"
            git apply -3 changes.patch
          fi

          git add -A
          if git diff --cached --quiet; then
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          else
            git commit -m "Apply patch from issue #${{ github.event.issue.number }}"
            echo "NO_CHANGES=false" >> $GITHUB_ENV
          fi

      - name: Push de la rama de trabajo
        if: env.NO_CHANGES == 'false'
        shell: bash
        run: |
          git push --set-upstream origin "$BRANCH"

      - name: Crear Pull Request
        if: env.NO_CHANGES == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.base.outputs.default_branch }}   # ← ahora viene del evento
          branch: ${{ env.BRANCH }}
          title: "Apply patch from issue #${{ github.event.issue.number }}"
          body: |
            This PR was generated automatically from issue #${{ github.event.issue.number }}.

      - name: Comentar en el issue si no hay cambios
        if: env.NO_CHANGES == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ El patch ya está aplicado o no produce cambios; no se creó PR.
