name: Apply patch from issue

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write        # push a ramas
  pull-requests: write   # abrir PRs
  issues: write          # comentar de vuelta al issue

jobs:
  apply:
    if: contains(github.event.issue.labels.*.name, 'apply-patch')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract patch from issue body
        id: extract
        run: |
          python3 - <<'PY'
          import os, re, sys, pathlib
          body = os.environ['BODY']
          m = re.search(r'```patch\s+([\s\S]+?)\s```', body)
          if not m:
            print("::error::No se encontró un bloque ```patch``` en el issue.")
            sys.exit(1)
          pathlib.Path("patch.diff").write_text(m.group(1))
          PY
        env:
          BODY: ${{ github.event.issue.body }}

      - name: Apply patch
        run: |
          set -e
          git config user.name  "patch-bot"
          git config user.email "bot@users.noreply.github.com"
          git checkout -b patch/${{ github.run_id }}
          git apply -p0 patch.diff
          git add -A
          git commit -m "Apply patch from issue #${{ github.event.issue.number }}"
          git push --set-upstream origin patch/${{ github.run_id }}

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          branch: patch/${{ github.run_id }}
          base: main
          title: "Patch from issue #${{ github.event.issue.number }} — ${{ github.event.issue.title }}"
          body: |
            Auto PR generado desde el issue #${{ github.event.issue.number }}.

