name: Apply patch from issue

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  apply:
    if: >
      (github.event_name == 'issues' &&
       contains(join(github.event.issue.labels.*.name), 'apply-patch')) ||
      (github.event_name == 'issue_comment' &&
       contains(github.event.issue.labels.*.name, 'apply-patch') &&
       contains(github.event.comment.body, '/apply'))
    runs-on: ubuntu-latest
    env:
      PATCH_BRANCH: patch-${{ github.event.issue.number || github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Extract patch from issue/comment body
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.comment?.body || context.payload.issue?.body || '');
            const m = body.match(/```patch([\s\S]*?)```/i);
            if (!m) core.setFailed('No se encontró un bloque ```patch``` en el issue/comment.');
            const fs = require('fs');
            fs.writeFileSync('chatgpt.patch', m[1].trim() + '\n');

      - name: Apply patch
        run: |
          git config user.name "Patch Bot"
          git config user.email "patch-bot@users.noreply.github.com"
          git checkout -b "$PATCH_BRANCH"
          git apply -p0 --whitespace=fix chatgpt.patch
          git add -A
          git commit -m "Apply patch from issue #${{ github.event.issue.number || github.run_id }}"
          git push --set-upstream origin "$PATCH_BRANCH"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.PATCH_BRANCH }}
          title: "Apply patch from issue #${{ github.event.issue.number || github.run_id }}"
          body: "PR automatizado desde issue con etiqueta `apply-patch`."
          base: main
