name: Apply patch from issue

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  apply:
    if: >
      (github.event_name == 'issues' && github.event.label.name == 'apply-patch') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/apply'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Extract patch from issue/comment
        id: patch
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const ev = context.payload;
            const body = context.eventName === 'issue_comment'
              ? (ev.comment?.body || '')
              : (ev.issue?.body || '');
            const m = body.match(/```patch\s+([\s\S]*?)```/i);
            if (!m) core.setFailed('No se encontró bloque ```patch``` en el issue/comentario.');
            core.setOutput('patch', m ? m[1] : '');

      - name: Save patch to file
        run: |
          printf "%s" "${PATCH}" > patch.diff
          echo "------ PATCH ------"; cat patch.diff; echo "-------------------"
        env:
          PATCH: ${{ steps.patch.outputs.patch }}

      - name: Create work branch
        run: |
          BR="patch/issue-${{ github.event.issue.number }}-${{ github.run_id }}"
          echo "BRANCH=$BR" >> $GITHUB_ENV
          git switch -c "$BR" || git checkout -b "$BR"

      - name: Apply patch
        run: |
          set -euxo pipefail
          git apply --whitespace=fix --index patch.diff

      - name: Commit
        run: |
          git commit -m "Apply patch from issue #${{ github.event.issue.number }}"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH }}
          title: "Apply patch from issue #${{ github.event.issue.number }}"
          body: "Automático desde issue #${{ github.event.issue.number }}"
          base: ${{ github.event.repository.default_branch }}
          labels: patch-bot
